<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>YrrpAnalyser.Cli</RootNamespace>
    <AssemblyName>yrrp</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\YrrpAnalyser.Core\YrrpAnalyser.Core.csproj" />
  </ItemGroup>
</Project>
